export const cars = [
    {
        id: 1,
        name: "BMW 7 Series",
        model: "2024",
        image: "/cars/bmw-7.jpg",
        mileage: "12 km/l",
        seats: 5,
        price: 550,
        pricePerHour: 550,
        fuel: "Petrol",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 2,
        name: "Mercedes-Benz E-Class",
        model: "2024",
        image: "/cars/mercedes-e.jpg",
        mileage: "11 km/l",
        seats: 5,
        price: 520,
        pricePerHour: 520,
        fuel: "Diesel",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 3,
        name: "Audi Q7",
        model: "2024",
        image: "/cars/audi-q7.jpg",
        mileage: "10 km/l",
        seats: 7,
        price: 600,
        pricePerHour: 600,
        fuel: "Diesel",
        category: "SUV",
        transmission: "Automatic",
    },
    {
        id: 4,
        name: "Jaguar XE",
        model: "2024",
        image: "/cars/jaguar-xe.jpg",
        mileage: "13 km/l",
        seats: 5,
        price: 480,
        pricePerHour: 480,
        fuel: "Petrol",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 5,
        name: "Range Rover Velar",
        model: "2024",
        image: "/cars/range-rover-velar.jpg",
        mileage: "9 km/l",
        seats: 5,
        price: 720,
        pricePerHour: 720,
        fuel: "Diesel",
        category: "SUV",
        transmission: "Automatic",
    },
    {
        id: 6,
        name: "Tesla Model S",
        model: "2024",
        image: "/cars/tesla-model-s.jpg",
        mileage: "6 km/kWh",
        seats: 5,
        price: 580,
        pricePerHour: 580,
        fuel: "Electric",
        category: "Electric",
        transmission: "Automatic",
    },
    // Added 15 more cars
    {
        id: 7,
        name: "Toyota Fortuner",
        model: "2024",
        image: "/cars/fortuner.png",
        mileage: "10 km/l",
        seats: 7,
        price: 450,
        pricePerHour: 450,
        fuel: "Diesel",
        category: "SUV",
        transmission: "Automatic",
    },
    {
        id: 8,
        name: "Mahindra Thar",
        model: "2024",
        image: "/cars/thar.png",
        mileage: "12 km/l",
        seats: 4,
        price: 380,
        pricePerHour: 380,
        fuel: "Diesel",
        category: "SUV",
        transmission: "Manual/Auto",
    },
    {
        id: 9,
        name: "Kia Seltos",
        model: "2024",
        image: "/cars/seltos.png",
        mileage: "14 km/l",
        seats: 5,
        price: 350,
        pricePerHour: 350,
        fuel: "Petrol",
        category: "SUV",
        transmission: "Automatic",
    },
    {
        id: 10,
        name: "Honda City",
        model: "2024",
        image: "/cars/city.png",
        mileage: "16 km/l",
        seats: 5,
        price: 300,
        pricePerHour: 300,
        fuel: "Petrol",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 11,
        name: "Hyundai Verna",
        model: "2024",
        image: "/cars/verna.png",
        mileage: "15 km/l",
        seats: 5,
        price: 320,
        pricePerHour: 320,
        fuel: "Diesel",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 12,
        name: "VW Virtus",
        model: "2024",
        image: "/cars/virtus.png",
        mileage: "18 km/l",
        seats: 5,
        price: 340,
        pricePerHour: 340,
        fuel: "Petrol",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 13,
        name: "Hyundai i20",
        model: "2024",
        image: "/cars/i20.png", // dedicated image
        mileage: "20 km/l",
        seats: 5,
        price: 250,
        pricePerHour: 250,
        fuel: "Petrol",
        category: "Hatchback",
        transmission: "Manual",
    },
    {
        id: 14,
        name: "Suzuki Swift",
        model: "2024",
        image: "/cars/bmw-7.jpg", // placeholder
        mileage: "22 km/l",
        seats: 5,
        price: 220,
        pricePerHour: 220,
        fuel: "Petrol",
        category: "Hatchback",
        transmission: "Automatic",
    },
    {
        id: 15,
        name: "Tata Altroz",
        model: "2024",
        image: "/cars/mercedes-e.jpg", // placeholder
        mileage: "21 km/l",
        seats: 5,
        price: 240,
        pricePerHour: 240,
        fuel: "Petrol",
        category: "Hatchback",
        transmission: "Manual",
    },
    {
        id: 16,
        name: "Nexon EV",
        model: "2024",
        image: "/cars/tesla-model-s.jpg", // placeholder
        mileage: "312 km/charge",
        seats: 5,
        price: 360,
        pricePerHour: 360,
        fuel: "Electric",
        category: "Electric",
        transmission: "Automatic",
    },
    {
        id: 17,
        name: "MG ZS EV",
        model: "2024",
        image: "/cars/mg-zs-ev.png", // unique image
        mileage: "461 km/charge",
        seats: 5,
        price: 420,
        pricePerHour: 420,
        fuel: "Electric",
        category: "Electric",
        transmission: "Automatic",
    },
    {
        id: 18,
        name: "Kia EV6",
        model: "2024",
        image: "/cars/kia-ev6.png", // unique image
        mileage: "528 km/charge",
        seats: 5,
        price: 650,
        pricePerHour: 650,
        fuel: "Electric",
        category: "Electric",
        transmission: "Automatic",
    },
    {
        id: 19,
        name: "Scorpio-N",
        model: "2024",
        image: "/cars/audi-q7.jpg", // placeholder
        mileage: "13 km/l",
        seats: 7,
        price: 400,
        pricePerHour: 400,
        fuel: "Diesel",
        category: "SUV",
        transmission: "Automatic",
    },
    {
        id: 20,
        name: "Skoda Slavia",
        model: "2024",
        image: "/cars/bmw-7.jpg", // placeholder
        mileage: "18 km/l",
        seats: 5,
        price: 330,
        pricePerHour: 330,
        fuel: "Petrol",
        category: "Sedan",
        transmission: "Automatic",
    },
    {
        id: 21,
        name: "VW Polo GTI",
        model: "2024",
        image: "/cars/mercedes-e.jpg", // placeholder
        mileage: "15 km/l",
        seats: 5,
        price: 280,
        pricePerHour: 280,
        fuel: "Petrol",
        category: "Hatchback",
        transmission: "Automatic",
    },
];

export const carsDatabase = {
    "1": {
        id: "1",
        name: "BMW 7 Series",
        model: "2024",
        category: "Luxury Sedan",
        price: 550,
        mileage: "12 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "3.0L Twin-Scroll Turbo",
        power: "340 HP",
        torque: "450 Nm",
        acceleration: "5.5 seconds (0-100 km/h)",
        topSpeed: "250 km/h",
        features: [
            "Leather Upholstery",
            "Panoramic Sunroof",
            "Adaptive Suspension",
            "Premium Sound System",
            "Advanced Driver Assistance",
            "Wireless Charging",
            "Ambient Lighting",
            "Air Suspension",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/bmw-7.jpg",
    },
    "2": {
        id: "2",
        name: "Mercedes-Benz E-Class",
        model: "2024",
        category: "Luxury Sedan",
        price: 520,
        mileage: "11 km/l",
        seats: 5,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "2.0L TwinPower Turbo",
        power: "299 HP",
        torque: "400 Nm",
        acceleration: "6.1 seconds (0-100 km/h)",
        topSpeed: "250 km/h",
        features: [
            "Nappa Leather",
            "Panoramic Sunroof",
            "AIRMATIC Suspension",
            "Harman Kardon Sound",
            "Active Distance Assist",
            "Power Seats",
            "Ambient Light",
            "Parktronic",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/mercedes-e.jpg",
    },
    "3": {
        id: "3",
        name: "Audi Q7",
        model: "2024",
        category: "Luxury SUV",
        price: 600,
        mileage: "10 km/l",
        seats: 7,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "3.0L TDI Quattro",
        power: "272 HP",
        torque: "600 Nm",
        acceleration: "6.5 seconds (0-100 km/h)",
        topSpeed: "240 km/h",
        features: [
            "Leather Interior",
            "Panoramic Sunroof",
            "Adaptive Air Suspension",
            "Bang & Olufsen Sound",
            "Audi Pre Sense",
            "Power Seats",
            "Ambient Lighting",
            "Matrix LED",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/audi-q7.jpg",
    },
    "4": {
        id: "4",
        name: "Jaguar XE",
        model: "2024",
        category: "Sports Sedan",
        price: 480,
        mileage: "13 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "2.0L Ingenium",
        power: "250 HP",
        torque: "365 Nm",
        acceleration: "6.8 seconds (0-100 km/h)",
        topSpeed: "240 km/h",
        features: [
            "Leather Upholstery",
            "Panoramic Sunroof",
            "Adaptive Dynamics",
            "Meridian Sound System",
            "Adaptive Headlights",
            "Power Seats",
            "Ambient Mood Lighting",
            "Touchscreen",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/jaguar-xe.jpg",
    },
    "5": {
        id: "5",
        name: "Range Rover Velar",
        model: "2024",
        category: "Luxury SUV",
        price: 720,
        mileage: "9 km/l",
        seats: 5,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "3.0L TDI Diesel",
        power: "249 HP",
        torque: "600 Nm",
        acceleration: "7.1 seconds (0-100 km/h)",
        topSpeed: "230 km/h",
        features: [
            "Premium Leather",
            "Panoramic Sunroof",
            "Air Suspension",
            "Meridian Surround Sound",
            "All-Terrain Progress",
            "Power Seats",
            "Interactive Ambient Light",
            "Touchscreen InControl",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/range-rover-velar.jpg",
    },
    "6": {
        id: "6",
        name: "Tesla Model S",
        model: "2024",
        category: "Electric Luxury",
        price: 580,
        mileage: "6 km/kWh",
        seats: 5,
        fuel: "Electric",
        transmission: "Automatic",
        engine: "Dual Motor",
        power: "500+ HP",
        torque: "660 Nm",
        acceleration: "3.2 seconds (0-100 km/h)",
        topSpeed: "250 km/h",
        features: [
            "Premium Interior",
            "Panoramic Glass Roof",
            "Air Suspension",
            " Premium Audio",
            "Autopilot",
            "Power Seats",
            "Ambient Lighting",
            "Touchscreen Interface",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/tesla-model-s.jpg",
    },
    "17": {
        id: "17",
        name: "MG ZS EV",
        model: "2024",
        category: "Electric SUV",
        price: 420,
        mileage: "461 km/charge",
        seats: 5,
        fuel: "Electric",
        transmission: "Automatic",
        engine: "50.3 kWh Battery",
        power: "176 HP",
        torque: "280 Nm",
        acceleration: "8.5 seconds (0-100 km/h)",
        topSpeed: "140 km/h",
        features: [
            "Leatherette Upholstery",
            "Panoramic Sunroof",
            "i-SMART Next Gen",
            "360 Degree Camera",
            "PM 2.5 Filter",
            "Electric Adjustment Seats",
            "Wireless Charging",
            "Heated Mirrors",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/mg-zs-ev.png",
    },
    "18": {
        id: "18",
        name: "Kia EV6",
        model: "2024",
        category: "Electric Crossover",
        price: 650,
        mileage: "528 km/charge",
        seats: 5,
        fuel: "Electric",
        transmission: "Automatic",
        engine: "77.4 kWh Battery",
        power: "325 HP",
        torque: "605 Nm",
        acceleration: "5.2 seconds (0-100 km/h)",
        topSpeed: "185 km/h",
        features: [
            "Vegan Leather Seats",
            "Curved Display",
            "Augmented Reality HUD",
            "Meridian Premium Sound",
            "Remote Smart Park",
            "V2L (Vehicle-to-Load)",
            "Ambient Light",
            "Smart Cruise Control",
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/kia-ev6.png",
    },
    "7": {
        id: "7",
        name: "Toyota Fortuner",
        model: "2024",
        category: "SUV",
        price: 450,
        mileage: "10 km/l",
        seats: 7,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/fortuner.png",
    },
    "8": {
        id: "8",
        name: "Mahindra Thar",
        model: "2024",
        category: "SUV",
        price: 380,
        mileage: "12 km/l",
        seats: 4,
        fuel: "Diesel",
        transmission: "Manual/Auto",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/thar.png",
    },
    "9": {
        id: "9",
        name: "Kia Seltos",
        model: "2024",
        category: "SUV",
        price: 350,
        mileage: "14 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/seltos.png",
    },
    "10": {
        id: "10",
        name: "Honda City",
        model: "2024",
        category: "Sedan",
        price: 300,
        mileage: "16 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/city.png",
    },
    "11": {
        id: "11",
        name: "Hyundai Verna",
        model: "2024",
        category: "Sedan",
        price: 320,
        mileage: "15 km/l",
        seats: 5,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/verna.png",
    },
    "12": {
        id: "12",
        name: "VW Virtus",
        model: "2024",
        category: "Sedan",
        price: 340,
        mileage: "18 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/virtus.png",
    },
    "13": {
        id: "13",
        name: "Hyundai i20",
        model: "2024",
        category: "Hatchback",
        price: 250,
        mileage: "20 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Manual",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/i20.png",
    },
    "14": {
        id: "14",
        name: "Suzuki Swift",
        model: "2024",
        category: "Hatchback",
        price: 220,
        mileage: "22 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/bmw-7.jpg",
    },
    "15": {
        id: "15",
        name: "Tata Altroz",
        model: "2024",
        category: "Hatchback",
        price: 240,
        mileage: "21 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Manual",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/mercedes-e.jpg",
    },
    "16": {
        id: "16",
        name: "Nexon EV",
        model: "2024",
        category: "Electric",
        price: 360,
        mileage: "312 km/charge",
        seats: 5,
        fuel: "Electric",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/tesla-model-s.jpg",
    },
    "19": {
        id: "19",
        name: "Scorpio-N",
        model: "2024",
        category: "SUV",
        price: 400,
        mileage: "13 km/l",
        seats: 7,
        fuel: "Diesel",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/audi-q7.jpg",
    },
    "20": {
        id: "20",
        name: "Skoda Slavia",
        model: "2024",
        category: "Sedan",
        price: 330,
        mileage: "18 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/bmw-7.jpg",
    },
    "21": {
        id: "21",
        name: "VW Polo GTI",
        model: "2024",
        category: "Hatchback",
        price: 280,
        mileage: "15 km/l",
        seats: 5,
        fuel: "Petrol",
        transmission: "Automatic",
        engine: "Standard Spec",
        power: "N/A",
        torque: "N/A",
        acceleration: "N/A",
        topSpeed: "N/A",
        features: [
            "Premium Upholstery",
            "Advanced Infotainment",
            "Safety Package"
        ],
        insurance: "Comprehensive Coverage Included",
        cancellation: "Free Cancellation up to 24 hours",
        image: "/cars/mercedes-e.jpg",
    },
};
